### ISSUE TITLE
edge tiles don't load with zoom delta < 1

### ISSUE THREAD

**Issue by rheinheimer** [Charmatzis/react-leaflet-google#25]
When react-leaflet's zoomDelta is, say, 0.5, Google tile layers often (presumably at half-level zooms) do not cover the entire view (see screenshot). For now, my solution is, of course, to use zoomDelta=1, but this should probably be fixed.

![image](https://user-images.githubusercontent.com/9124277/38461449-5a18c5be-3a9e-11e8-9935-163b89150f01.png)

**Comment by Charmatzis** [comment]
@rheinheimer Hi, I have updated the package with some latest fixes (3.3.0). I believe that now you are OK. Can you confirm it?

**Comment by rheinheimer** [comment]
@Charmatzis Apologies for the tardiness. The half-zoom issue remains.

**Comment by Charmatzis** [comment]
@rheinheimer  is this issue remains? I have done an update. 

If it remains, could you plz, develop a demo to test it?

**Comment by rheinheimer** [comment]
@Charmatzis Unfortunately the update seems to depends on react-leaflet 2.0, not 1.x, which breaks the customizations in my app. So there's no way for me to test this. What changes did you make to fix this?
